kind: pipeline
name: default

steps:
- name: ci
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  volumes:
    - name: socket
      path: /var/run/docker.sock

- name: github_binary_prerelease
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/*"
    prerelease: true
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    checksum:
    - sha256
    files:
    - "bin/*"
    api_key:
      from_secret: github_token
  when:
    event:
    - tag
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
